name: CI - API Gateway

on:
  push:
    branches: [ dev, test, main ]
    paths:
      - 'backend/api-gateway/**'
      - '.github/workflows/gateway-ci.yml'

jobs:
  build-push-and-update-secrets:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push api-gateway image
      uses: docker/build-push-action@v5
      with:
        context: ./backend/api-gateway
        push: true
        tags: |
          luca011/api-gateway-atales:${{ github.ref_name == 'main' && 'prod' || github.ref_name }}-latest

    - name: Checkout repo de infraestructura
      uses: actions/checkout@v3
      with:
        repository: LucaCostabile/infrastructura-Atales
        path: infra
        token: ${{ secrets.PAT_GITHUB }}

    - name: Generar Secret YAML
      run: |
        mkdir -p infra/secrets/dev
        cat <<EOF > infra/secrets/dev/gateway-secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: gateway-secrets
  namespace: dev
type: Opaque
data:
  JWT_SECRET_KEY: $(echo -n "${{ secrets.JWT_SECRET_KEY }}" | base64)
EOF

    - name: Commit y push al repo de infraestructura
      run: |
        cd infra
        git config user.email "lucacostabile011@gmail.com"
        git config user.name "Luca Costabile"
        git add secrets/dev/gateway-secrets.yaml
        git commit -m "ci(gateway): actualiza secretos"
        git push
